{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rubrion.common",
    "module": "common",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.1.jar",
          "url": "common-1.0.1.jar",
          "size": 696,
          "sha512": "f285a999490d934aad32e02aeb454c47de42c170ac35761be0c0cd1f97c4b4d1fc6a81d4ce6641f2b91bdf2cf77b876e3a5ec6204c9c6de0b5e4ec198f57302a",
          "sha256": "6fcacab137372d1af5c8c9f45a53faf55e6b1fd854c22fb3738722171fdbda21",
          "sha1": "12013c5f737d3e125a7e05b27d358768f51bd17b",
          "md5": "63aadb5a1df92901ad86c5ce4b33a6a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.rubrion.common",
          "module": "api",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1.jar",
          "url": "common-1.0.1.jar",
          "size": 696,
          "sha512": "f285a999490d934aad32e02aeb454c47de42c170ac35761be0c0cd1f97c4b4d1fc6a81d4ce6641f2b91bdf2cf77b876e3a5ec6204c9c6de0b5e4ec198f57302a",
          "sha256": "6fcacab137372d1af5c8c9f45a53faf55e6b1fd854c22fb3738722171fdbda21",
          "sha1": "12013c5f737d3e125a7e05b27d358768f51bd17b",
          "md5": "63aadb5a1df92901ad86c5ce4b33a6a9"
        }
      ]
    }
  ]
}
