{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rubrion.common",
    "module": "api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 8965,
          "sha512": "9093d4cfbdd29c6ec646484286a8d1ba32bc64b8bb7adf9291e96beba6a7593a92968e15815aaf40be1c15bd7ae41251a4b5deba9f01696eb0872d05ec458767",
          "sha256": "0973adc40ba6762b352375c2aad2daf66cd90671ddc942b462e7f1e2a7ee7137",
          "sha1": "43aa28e6eff1dd6074366da4dc131279dd8f0c80",
          "md5": "3b1f8ee9b12bb0a7612afba464211d39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 8965,
          "sha512": "9093d4cfbdd29c6ec646484286a8d1ba32bc64b8bb7adf9291e96beba6a7593a92968e15815aaf40be1c15bd7ae41251a4b5deba9f01696eb0872d05ec458767",
          "sha256": "0973adc40ba6762b352375c2aad2daf66cd90671ddc942b462e7f1e2a7ee7137",
          "sha1": "43aa28e6eff1dd6074366da4dc131279dd8f0c80",
          "md5": "3b1f8ee9b12bb0a7612afba464211d39"
        }
      ]
    }
  ]
}
