{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rubrion.common",
    "module": "api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 19368,
          "sha512": "a2564da08ccfdde25fea705a8b9daac11472cda85e551f475bb24776de4b9d250bcccd962855e1b1efd4d5c4472b7df8d43132de17e4903f4e9feccbcfb44c29",
          "sha256": "10b10ae34d5fe0865bc0c76068d610d1ef4fe046b8596e39f2bd1f8082e0ba45",
          "sha1": "0ead2770e689e801bdf3a1fa7085fa4f82c0312c",
          "md5": "8a296ed51679774739afebf7c66d08b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 19368,
          "sha512": "a2564da08ccfdde25fea705a8b9daac11472cda85e551f475bb24776de4b9d250bcccd962855e1b1efd4d5c4472b7df8d43132de17e4903f4e9feccbcfb44c29",
          "sha256": "10b10ae34d5fe0865bc0c76068d610d1ef4fe046b8596e39f2bd1f8082e0ba45",
          "sha1": "0ead2770e689e801bdf3a1fa7085fa4f82c0312c",
          "md5": "8a296ed51679774739afebf7c66d08b0"
        }
      ]
    }
  ]
}
